name: Claude Mode Examples

on:
  # Common events for both modes
  issue_comment:
    types: [created]
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened]

jobs:
  # Tag Mode (Default) - Traditional implementation
  tag-mode-example:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Tag mode (default) behavior:
          # - Scans for @claude mentions in comments, issues, and PRs
          # - Only acts when trigger phrase is found
          # - Creates tracking comments with progress checkboxes
          # - Perfect for: Interactive Q&A, on-demand code changes

  # Tag Mode with Direct Prompt - Automation without trigger scanning
  tag-mode-auto-review:
    # Automatically review every new PR
    # NOTE: Agent mode is currently broken. Use tag mode with direct_prompt instead.
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - uses: anthropics/claude-code-action@beta
        with:
          mode: tag
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          direct_prompt: |
            Review this PR for code quality. Focus on:
            - Potential bugs or logic errors
            - Security concerns
            - Performance issues

            Provide specific, actionable feedback.
          # Tag mode with direct_prompt behavior:
          # - NO @claude mention needed - runs immediately with the provided prompt
          # - Enables automation without trigger phrase scanning
          # - Perfect for: CI/CD integration, automatic reviews, label-based workflows
